### ISSUE TITLE
availability on pypi

### ISSUE THREAD

**Issue by nschloe** [xtensor-stack/xtensor-python#219]
What prevents xtensor-python to be installed via pypi?

**Comment by SylvainCorlay** [comment]
xtensor-python is not a python package!

**Comment by nschloe** [comment]
I see. 

> xtensor-python is a header-only library. We provide a package for the conda package manager.

I got confused by the fact that you're providing a conda package.

**Comment by SylvainCorlay** [comment]
> I got confused by the fact that you're providing a conda package.

In fact, conda is a general purpose package manager.
Conda forge includes many non-python packages such as R and thousands of R packages, or as many native packages.

**Comment by AntoinePrv** [comment]
Hello,

I'm in the process of learning about PyPI, source and binary distributions, *etc.* as I will need to figure some of it for a project of ours.

[CMake](https://pypi.org/project/cmake/) and [PyBind11](https://pypi.org/project/pybind11/) are also not Python packages but they ship on PyPI to easily resolve build dependencies on user computer.
I believe in the case of `xtensor-python`, the idea would be the same, to be able to ship source distribution that will build with an `xtensor-python` extension.
Of course, this would need to also resolve `xtensor`, *etc.* so it is not easy.

An idea I'm thinking about is to use `conan` inside a `setup.py`, as `conan` is written in Python, but that might get out of scope for this issue.
Would be happy to discuss more if you're interested.
