### ISSUE TITLE
Release to Pybind 2.5

### ISSUE THREAD

**Issue by AntoinePrv** [xtensor-stack/xtensor-python#240]
Hello,

Using `xtensor-python` from conda pins `pybind11<2.5`
https://github.com/conda-forge/xtensor-python-feedstock/blob/90132ec1e68d0e190f2155293c2ff7c896639050/recipe/meta.yaml#L26

Unfortunately, `pybind11<2.5` has a bug with C++17 on MacOS
https://github.com/pybind/pybind11/pull/2038

Let me know if I can be of assistance.
Alternatively, is there a reason to maintain such a strict pin on `pybind11`?

**Comment by SylvainCorlay** [comment]
Hey @AntoinePrv thanks for reporting.

I don't remember why we needed PyBind11<2.5. I think that it is worth trying releasing that constraints in a PR to the feedstock.

Although I think we should keep at least an upper bound with the next (unreleased) major release.
