### ISSUE TITLE
Doesn't install the python binding

### ISSUE THREAD

**Issue by yurivict** [xtensor-stack/xtensor-python#271]
Version 0.26.0 only installs these files:
```
include/xtensor-python/pyarray.hpp
include/xtensor-python/pyarray_backstrides.hpp
include/xtensor-python/pycontainer.hpp
include/xtensor-python/pynative_casters.hpp
include/xtensor-python/pystrides_adaptor.hpp
include/xtensor-python/pytensor.hpp
include/xtensor-python/pyvectorize.hpp
include/xtensor-python/xtensor_python_config.hpp
include/xtensor-python/xtensor_type_caster_base.hpp
lib/cmake/xtensor-python/xtensor-pythonConfig.cmake
lib/cmake/xtensor-python/xtensor-pythonConfigVersion.cmake
lib/cmake/xtensor-python/xtensor-pythonTargets.cmake
```

The actual python binding files are missing.

**Comment by SylvainCorlay** [comment]
Thanks for opening the issues on various xtensor repositories.

This one seems like the expected behavior. Xtensor-python does not include python bindings. It is a header-only library that allows you to operate on numpy arrays in-place using xtensor syntax, in C++ extensions.

**Comment by yurivict** [comment]
Perhaps you should consider to correct the project description to how you described it above.
The current description says that it is python bindings.

**Comment by SylvainCorlay** [comment]
Well these *are* python bindings but not in the way you meant it! It does not include a python package.

**Comment by yurivict** [comment]
Thank you for your explanation.
